### ISSUE TITLE
Cool Project !

### ISSUE THREAD

**Issue by RockNHawk** [tg123/IronLeveldb#1]
A pure C implementation can avoid the performance penalty of PInvoke and byte[] copies from native to managed. Thanks for your great work!

And could you tell me how can I implement SeekLast() method ?

            return SeekToRestartPoint(_numRestarts - 1);

**Comment by tg123** [comment]
the reason I did not implement `seeklast` is that there is no `backward iterator` at the moment.
after you seek to last block, you may need to iter to last entry of that block to reach the `last`

see also
https://github.com/google/leveldb/blob/863f185970eff21e826e5fe1164a6215a515c23b/table/block.cc#L210

**Comment by RockNHawk** [comment]
@tg123 Thank you !
